export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_COMPANY_PROFILE_DATA = 'SET_COMPANY_PROFILE_DATA';
export const CLEAR_COMPANY_PROFILE_DATA = 'CLEAR_COMPANY_PROFILE_DATA';

export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_SPECIFIC_JOB = 'GET_SPECIFIC_JOB';
export const GET_SEARCHED_JOB = 'GET_SEARCHED_JOB';
export const SAVE_JOB = 'SAVE_JOB';
export const UNSAVE_JOB = 'UNSAVE_JOB';
export const STORE_SEARCHED_RESULTS = 'STORE_SEARCHED_RESULTS';
