export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_COMPANY_PROFILE_DATA = 'SET_COMPANY_PROFILE_DATA';
export const CLEAR_COMPANY_PROFILE_DATA = 'CLEAR_COMPANY_PROFILE_DATA';
export const SET_CHAT_ROOMS = 'SET_CHAT_ROOMS';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const SET_SENDER = 'SET_SENDER';
export const SET_RECEIVER = 'SET_RECEIVER';

export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_SPECIFIC_JOB = 'GET_SPECIFIC_JOB';
export const GET_SEARCHED_JOB = 'GET_SEARCHED_JOB';
export const SAVE_JOB = 'SAVE_JOB';
export const UNSAVE_JOB = 'UNSAVE_JOB';
export const STORE_SEARCHED_RESULTS = 'STORE_SEARCHED_RESULTS';

export const POST_REVIEW = 'POST_REVIEW';
export const POST_JOB = 'POST_JOB';
export const GET_REVIEW = 'GET_REVIEW';
