export const CLEAR_USER_DETAILS = 'CLEAR_USER_DETAILS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_COMPANY_PROFILE_DATA = 'SET_COMPANY_PROFILE_DATA';
export const CLEAR_COMPANY_PROFILE_DATA = 'CLEAR_COMPANY_PROFILE_DATA';
export const SET_CHAT_ROOMS = 'SET_CHAT_ROOMS';
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const UPDATE_CONVERSATION = 'UPDATE_CONVERSATION';
export const SET_SENDER = 'SET_SENDER';
export const SET_RECEIVER = 'SET_RECEIVER';
export const CREATE_ROOM = 'CREATE_ROOM';
export const OPEN_MESSAGE_BOX = 'OPEN_MESSAGE_BOX';

export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const GET_COMPANY_SPECIFIC_JOBS = 'GET_COMPANY_SPECIFIC_JOBS';
export const GET_SPECIFIC_JOB = 'GET_SPECIFIC_JOB';
export const GET_SEARCHED_JOB = 'GET_SEARCHED_JOB';
export const SAVE_JOB = 'SAVE_JOB';
export const UNSAVE_JOB = 'UNSAVE_JOB';
export const STORE_SEARCHED_RESULTS = 'STORE_SEARCHED_RESULTS';
export const FEATURE_A_REVIEW = 'FEATURE_A_REVIEW';

export const POST_REVIEW = 'POST_REVIEW';
export const POST_JOB = 'POST_JOB';
export const GET_REVIEW = 'GET_REVIEW';

export const SET_EXTERNAL_COMPANY_PROFILE = 'SET_EXTERNAL_COMPANY_PROFILE';
export const CLEAR_EXTERNAL_COMPANY_PROFILE = 'CLEAR_EXTERNAL_COMPANY_PROFILE';

export const GET_FEATURED_REVIEWS = 'GET_FEATURED_REVIEWS';
export const SET_FIND_SALARIES_ACTION = 'SET_FIND_SALARIES_ACTION';
export const CLEAR_FIND_SALARIES_ACTION = 'CLEAR_FIND_SALARIES_ACTION';

export const UPLOAD_RESUME = 'UPLOAD_RESUME';

export const APPLY_FOR_JOB = 'APPLY_FOR_JOB';
