export const baseUrl = 'http://localhost:3003/';
export const urls = {
  register: 'indeed/user/UserRegistration',
  login: 'indeed/user/UserLogin',
  updateCompanyProfile: 'indeed/api/company',
  getCompaniesWithNameOrLocation: 'indeed/api/companiesList',
  getAllJobs: 'indeed/api/jobs',
  getSpecificJob: 'indeed/api/company',
  getCompanySpecificJobs: 'indeed/api/company',
  getSearchedJobs: 'indeed/api/jobs',
  getReviews: 'indeed/api/jobseeker',
  saveJob: 'indeed/api/jobseeker',
  unsaveJob: '',
  featureReview: 'indeed/api/reviews',
  fetchFeatured: 'indeed/api/jobseeker',
  reviewHelpful: 'indeed/api/reviews',
  getMyJobs: 'indeed/api/jobseeker/getAppliedJob',
  getMyReviews: 'indeed/api/jobseeker/reviews',
  postReview: 'indeed/api/jobseeker',
  uploadCompanyPhotos: 'indeed/api/uploadCompanyPhotos/{companyId}',
  imageUpload: 'indeed/files/upload/images',
  getCompanyDetailsByEmployerId:
    'indeed/api/companyDetails/forEmployer/{employerid}',
  getUserDetailsWithId: 'indeed/user/UserDetailsForId/{userId}',
  getCompanyDetailsByCompanyId: 'indeed/api/companyDetails/{companyId}',
  getImageFromS3: 'indeed/files/images/{key}',
  updateUserDetailsWithId: '',
  fetchReviewByUserId: '',
  findSalaries: 'indeed/api/salaries/jobs',
  uploadResume: 'indeed/files/upload/resume',
  updateUserProfile: 'indeed/api/userProfile',
  getProfile: 'indeed/api/jobseeker/profile',
  applyJob: 'indeed/api/jobseeker',
};
